---
functions:
  - inventory
  - automation

components:
  - podman
  - nautobot
  - postgresql
  - redis
  - restic
  - munin-node
  - webmin
  - needrestart
  - watchdog

ansible_python_interpreter: /usr/bin/python3
