---
- name: Single-host storage transport validate
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  serial: 1
  roles:
    - role: ../roles/storage_transport
      storage_stage: validate
