---
all:
  children:
    dns:
      hosts:
        pihole0:
          management_fqdn: pihole0.local.theama.co
        pihole00:
          management_fqdn: pihole00.local.theama.co

    reverse_proxy:
      hosts:
        pihole0: {}
        pihole00: {}

    monitoring:
      hosts:
        monitoring:
          management_fqdn: monitoring.local.theama.co

    notification:
      hosts:
        notification:
          management_fqdn: notification.local.theama.co

    inventory_automation:
      hosts:
        j2-svpi4mf:
          management_fqdn: j2-svpi4mf.local.theama.co
