name: "📝 Documentation Issue"
description: "Report an error or suggest an improvement for the documentation."
title: "[Docs] "
labels: ["documentation", "good first issue"]
assignees:
  - Racerx323
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve our documentation! Clear and accurate documentation is crucial for the project.

  - type: input
    id: url
    attributes:
      label: "Documentation URL"
      description: "Please provide the full URL of the documentation page where you found the issue."
      placeholder: "e.g., https://docs.example.com/path/to/page.html"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: "Type of Issue"
      description: "What kind of issue is this?"
      options:
        - "Typo or grammatical error"
        - "Incorrect information or code example"
        - "Missing content or section"
        - "Confusing or unclear explanation"
        - "Broken link, image, or formatting"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: "Description of the Issue"
      description: "Please provide a clear and concise description of what is wrong with the documentation."
      placeholder: "In the 'Advanced Configuration' section, the example for the API key is incorrect."
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: "Suggested Improvement"
      description: "How do you think we can improve the documentation? Please provide the corrected text, code, or a detailed explanation of the change."
      placeholder: "The example should be `API_KEY='your-key-here'` instead of `API-KEY=\"your-key-here\"`."

  - type: checkboxes
    id: pre-submission
    attributes:
      label: "Pre-submission Checklist"
      description: "Please confirm the following before submitting."
      options:
        - label: "I have searched the existing [documentation issues](https://github.com/Racerx323/homelab-server-configs/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation) to ensure this is not a duplicate."
          required: true
        - label: "I would be willing to submit a Pull Request to fix this issue."
          required: false
        - label: "I agree to follow this project's Code of Conduct."
          required: true