#!/usr/bin/env bash

set -Eeuo pipefail
set +x
umask 077
PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH
readonly PATH

readonly prefix=action_26_c_a_regression
test_directory=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
readonly test_directory
readonly caddy_root=${test_directory%/tests}
readonly core=$caddy_root/scripts/inspect-workstation-wsl-mirrored-postinstall-action26-c-a.sh
readonly candidate=$caddy_root/configs/wsl/.wslconfig
readonly candidate_sha256=6dffdf2bfc174eaca2a0bfcf8fe224929fd1006fbb48e3ccf34d642d234ab8a7

record_check() {
    local action26ca_regression_label=$1

    shift
    if "$@" >/dev/null; then
        printf '%s_%s=true\n' "$prefix" "$action26ca_regression_label"
        return 0
    fi
    printf '%s_%s=false\n' "$prefix" "$action26ca_regression_label" >&2
    return 1
}
create_fixture() {
    local action26ca_regression_name=$1
    local action26ca_regression_fixture=$action26ca_regression_root/$action26ca_regression_name

    install -d -m 0700 "$action26ca_regression_fixture/windows" \
        "$action26ca_regression_fixture/backup"
    chmod 0700 "$action26ca_regression_fixture/backup"
    cp -- "$candidate" "$action26ca_regression_fixture/windows/.wslconfig"
    printf 'action=26c\nbaseline=absent\ncandidate_sha256=%s\n' "$candidate_sha256" \
        >"$action26ca_regression_fixture/backup/manifest"
    chmod 0600 "$action26ca_regression_fixture/backup/manifest"
    printf 'Linux version test-microsoft-standard-WSL2\n' \
        >"$action26ca_regression_fixture/proc-version"
    printf '\n[boot]\nsystemd=true\n' >"$action26ca_regression_fixture/wsl.conf"
    cat >"$action26ca_regression_fixture/resolv-target" <<'EOF'
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 10.255.255.254
search local.theama.co
EOF
    ln -s "$action26ca_regression_fixture/resolv-target" \
        "$action26ca_regression_fixture/resolv.conf"
}
run_fixture() {
    local action26ca_regression_name=$1
    shift
    local action26ca_regression_fixture=$action26ca_regression_root/$action26ca_regression_name

    env "$@" \
        CADDY_ACTION26CA_TARGET="$action26ca_regression_fixture/windows/.wslconfig" \
        CADDY_ACTION26CA_BACKUP_ROOT="$action26ca_regression_fixture/backup" \
        CADDY_ACTION26CA_PROC_VERSION_PATH="$action26ca_regression_fixture/proc-version" \
        CADDY_ACTION26CA_WSL_CONF_PATH="$action26ca_regression_fixture/wsl.conf" \
        CADDY_ACTION26CA_RESOLV_CONF_PATH="$action26ca_regression_fixture/resolv.conf" \
        CADDY_ACTION26CA_RESOLV_LINK_TARGET="$action26ca_regression_fixture/resolv-target" \
        CADDY_ACTION26CA_WSLINFO_BIN="$action26ca_regression_root/fake-wslinfo" \
        CADDY_ACTION26CA_IP_BIN="$action26ca_regression_root/fake-ip" \
        /bin/bash "$core" >"$action26ca_regression_fixture/stdout" \
        2>"$action26ca_regression_fixture/stderr"
}

action26ca_regression_root=$(mktemp -d /tmp/caddy-action26-c-a-regression.XXXXXX)
readonly action26ca_regression_root
trap 'rm -rf -- "$action26ca_regression_root"' EXIT INT TERM

cat >"$action26ca_regression_root/fake-wslinfo" <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail
test "${1:-}" = --networking-mode
printf '%s\n' "${CADDY_ACTION26CA_FAKE_MODE:-nat}"
EOF
chmod 0700 "$action26ca_regression_root/fake-wslinfo"
cat >"$action26ca_regression_root/fake-ip" <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail
test "$*" = '-6 route get fd36:5aa8:6971:1::56'
printf 'RTNETLINK answers: Network is unreachable\n' >&2
exit "${CADDY_ACTION26CA_FAKE_ROUTE_STATUS:-2}"
EOF
chmod 0700 "$action26ca_regression_root/fake-ip"

create_fixture success
run_fixture success
record_check success_stderr_empty test ! -s "$action26ca_regression_root/success/stderr"
record_check acceptance grep -Fqx 'action_26_c_a_acceptance=true' \
    "$action26ca_regression_root/success/stdout"
record_check mode_nat grep -Fqx 'action_26_c_a_observed_networking_mode=nat' \
    "$action26ca_regression_root/success/stdout"
record_check route_status grep -Fqx 'action_26_c_a_observed_route_status=2' \
    "$action26ca_regression_root/success/stdout"
record_check target_unchanged cmp -s "$candidate" \
    "$action26ca_regression_root/success/windows/.wslconfig"
record_check shutdown_false grep -Fqx 'action_26_c_a_wsl_shutdown=false' \
    "$action26ca_regression_root/success/stdout"
record_check mutation_false grep -Fqx 'action_26_c_a_persistent_mutation=false' \
    "$action26ca_regression_root/success/stdout"

create_fixture wrong-target
printf '[wsl2]\nnetworkingMode=nat\n' >"$action26ca_regression_root/wrong-target/windows/.wslconfig"
if run_fixture wrong-target; then
    printf '%s_wrong_target_rejected=false\n' "$prefix" >&2
    exit 1
fi
printf '%s_wrong_target_rejected=true\n' "$prefix"

create_fixture wrong-manifest
sed -i 's/baseline=absent/baseline=present/' \
    "$action26ca_regression_root/wrong-manifest/backup/manifest"
if run_fixture wrong-manifest; then
    printf '%s_wrong_manifest_rejected=false\n' "$prefix" >&2
    exit 1
fi
printf '%s_wrong_manifest_rejected=true\n' "$prefix"

create_fixture wrong-resolver
sed -i 's/10[.]255[.]255[.]254/10.1.0.1/' \
    "$action26ca_regression_root/wrong-resolver/resolv-target"
if run_fixture wrong-resolver; then
    printf '%s_wrong_resolver_rejected=false\n' "$prefix" >&2
    exit 1
fi
printf '%s_wrong_resolver_rejected=true\n' "$prefix"

create_fixture already-active
if run_fixture already-active CADDY_ACTION26CA_FAKE_MODE=mirrored; then
    printf '%s_already_active_rejected=false\n' "$prefix" >&2
    exit 1
fi
printf '%s_already_active_rejected=true\n' "$prefix"

create_fixture route-present
if run_fixture route-present CADDY_ACTION26CA_FAKE_ROUTE_STATUS=0; then
    printf '%s_route_present_rejected=false\n' "$prefix" >&2
    exit 1
fi
printf '%s_route_present_rejected=true\n' "$prefix"

create_fixture residue
touch "$action26ca_regression_root/residue/windows/.wslconfig.action26c.stale"
if run_fixture residue; then
    printf '%s_residue_rejected=false\n' "$prefix" >&2
    exit 1
fi
printf '%s_residue_rejected=true\n' "$prefix"

record_check no_shutdown_command test \
    "$(grep -Eci 'wsl(\.exe)?[[:space:]]+--shutdown' "$core" || true)" -eq 0
record_check no_node_transport test \
    "$(grep -Eci '(^|[[:space:]])(ssh|scp|rsync)([[:space:]]|$)' "$core" || true)" -eq 0
printf '%s_complete=true\n' "$prefix"
